// frontend/src/app/(auth)/register/page.tsx
'use client';

import { useState } from 'react';
import { useAuth } from '@/hooks/useAuth';
import { Input } from '@/components/ui/Input';
import { Button } from '@/components/ui/Button';
import Link from 'next/link';
import { useRouter, useSearchParams } from 'next/navigation';

export default function RegisterPage() {
  const { register, login } = useAuth();
  const router = useRouter();
  const searchParams = useSearchParams();
  const defaultRole = searchParams.get('role') || 'buyer';

  const [form, setForm] = useState({
    name: '',
    email: '',
    password: '',
    role: defaultRole,
    phone: '',
    business_name: '',
    nit: '',
  });
  const [error, setError] = useState('');
  const [isLoading, setIsLoading] = useState(false);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError('');
    setIsLoading(true);

    try {
      await register(form);
      await login(form.email, form.password);
      router.push('/dashboard');
    } catch (err: any) {
      setError(err.message || 'Error al registrarse');
    } finally {
      setIsLoading(false);
    }
  };

  const updateField = (field: string, value: string) => {
    setForm((prev) => ({ ...prev, [field]: value }));
  };

  return (
    <div className="flex min-h-screen items-center justify-center bg-gray-50 px-4 py-8">
      <div className="w-full max-w-md">
        <div className="mb-8 text-center">
          <h1 className="text-3xl font-bold text-aqua-600">AcuaPlus</h1>
          <p className="mt-2 text-gray-600">Crea tu cuenta</p>
        </div>

        <form onSubmit={handleSubmit} className="card space-y-4">
          {error && (
            <div className="rounded-lg bg-red-50 p-3 text-sm text-red-700">
              {error}
            </div>
          )}

          <Input
            id="name"
            label="Nombre completo"
            value={form.name}
            onChange={(e) => updateField('name', e.target.value)}
            required
          />

          <Input
            id="email"
            label="Email"
            type="email"
            value={form.email}
            onChange={(e) => updateField('email', e.target.value)}
            required
          />

          <Input
            id="password"
            label="Contraseña"
            type="password"
            value={form.password}
            onChange={(e) => updateField('password', e.target.value)}
            required
            minLength={6}
          />

          <Input
            id="phone"
            label="Teléfono (opcional)"
            type="tel"
            value={form.phone}
            onChange={(e) => updateField('phone', e.target.value)}
          />

          <div>
            <label className="label">Tipo de cuenta</label>
            <div className="flex gap-4">
              <label className="flex items-center gap-2 cursor-pointer">
                <input
                  type="radio"
                  name="role"
                  value="buyer"
                  checked={form.role === 'buyer'}
                  onChange={(e) => updateField('role', e.target.value)}
                  className="text-aqua-600 focus:ring-aqua-500"
                />
                <span className="text-sm">Comprador</span>
              </label>
              <label className="flex items-center gap-2 cursor-pointer">
                <input
                  type="radio"
                  name="role"
                  value="seller"
                  checked={form.role === 'seller'}
                  onChange={(e) => updateField('role', e.target.value)}
                  className="text-aqua-600 focus:ring-aqua-500"
                />
                <span className="text-sm">Vendedor</span>
              </label>
            </div>
          </div>

          {form.role === 'seller' && (
            <>
              <Input
                id="business_name"
                label="Nombre del negocio"
                value={form.business_name}
                onChange={(e) => updateField('business_name', e.target.value)}
                required
              />
              <Input
                id="nit"
                label="NIT (opcional)"
                value={form.nit}
                onChange={(e) => updateField('nit', e.target.value)}
              />
              <p className="text-xs text-yellow-600">
                Los vendedores requieren aprobación del administrador antes de publicar productos.
              </p>
            </>
          )}

          <Button type="submit" className="w-full" isLoading={isLoading}>
            Crear cuenta
          </Button>

          <p className="text-center text-sm text-gray-600">
            ¿Ya tienes cuenta?{' '}
            <Link href="/login" className="font-medium text-aqua-600 hover:text-aqua-700">
              Iniciar sesión
            </Link>
          </p>
        </form>
      </div>
    </div>
  );
}

// acuaplus-frontend/src/app/auth/register/register.component.ts
import { Component } from '@angular/core';
import {FormBuilder, FormGroup, Validators} from "@angular/forms";
import {Router} from "@angular/router";
import {AuthService} from "../../core/services/auth.service";

@Component({
  selector: 'app-register',
  templateUrl: './register.component.html',
  styleUrls: ['./register.component.css']
})
export class RegisterComponent {

  form: FormGroup;
  loading = false;
  errorMsg = '';
  successMsg = '';

  constructor(private fb: FormBuilder, private authService: AuthService, private router: Router) {
    this.form = this.fb.group({
      name: ['', [Validators.required, Validators.minLength(2)]],
      email: ['', [Validators.required, Validators.email]],
      password: ['', [Validators.required, Validators.minLength(6)]],
      role: ['buyer', [Validators.required]],
      phone: [''],
      business_name: [''],
      nit: ['']
    });
  

this.form.get('role')!.valueChanges.subscribe(role => {
  this.updateSellerValidators(role);
});
}

get name() {return this.form.get('name')!;}
get email() {return this.form.get('email')!;}
get password() {return this.form.get('password')!;}
get role() {return this.form.get('role')!;}
get phone() {return this.form.get('phone')!;}
get business_name() {return this.form.get('business_name')!;}
get nit() {return this.form.get('nit')!;}

get isSeller(){
  return this.role.value === 'seller';
}

private updateSellerValidators(role: string) {
  const businessCtrl = this.form.get('business_name')!;
  const nitCtrl = this.form.get('nit')!;


if (role === 'seller') {
  businessCtrl.setValidators([Validators.required, Validators.minLength(2)]);
  nitCtrl.setValidators([Validators.required]);
} else {
  businessCtrl.clearValidators();
  nitCtrl.clearValidators();
}

businessCtrl.updateValueAndValidity();
nitCtrl.updateValueAndValidity();
}

onSubmit() {
  if (this.form.invalid) {
    this.form.markAllAsTouched();
    return;
  }
  this.loading = true;
  this.errorMsg = '';

  const raw = this.form.value;
  const payload: any = {
    name: raw.name,
    email: raw.email,
    password: raw.password,
    role: raw.role
  };
  if (raw.phone) payload.phone = raw.phone;
  if (raw.business_name) payload.business_name = raw.business_name;
  if (raw.nit) payload.nit = raw.nit;
this.authService.register(payload).subscribe({
  next: (res) => {
    this.loading = false;
    if (raw.role === 'seller') {
      this.successMsg = 'Registro exitoso. Tu cuenta está pendiente de aprobación por el administrador. Te notificaremos por correo electrónico una vez que tu cuenta sea aprobada.';
    } else {
      this.router.navigate(['/auth/login'], { queryParams: {registered: 'true'}
      });
    }
  }, error: (err) => {
    this.loading = false;
    this.errorMsg = err.error?.message || 'Error al registrar. Por favor, intenta nuevamente.';
  }
});
}
}
<div class="min-vh-100 d-flex align-items-center justify-content-center bg-light py-4">
  <div class="card shadow-sm" style="width: 100%; max-width: 480px;">
    <div class="card-body p-4 p-md-5">

      <!-- Título -->
      <div class="text-center mb-4">
        <span class="fs-2">💧</span>
        <h1 class="h4 fw-bold mt-2 mb-1">Crear cuenta</h1>
        <p class="text-muted small">Únete a Acuaplus</p>
      </div>

      <!-- Alerta de error -->
      <div *ngIf="errorMsg" class="alert alert-danger py-2 small">{{ errorMsg }}</div>

      <!-- Alerta de éxito (para vendedores pendientes) -->
      <div *ngIf="successMsg" class="alert alert-success small">
        <i class="bi bi-check-circle me-1"></i> {{ successMsg }}
        <div class="mt-2">
          <a routerLink="/auth/login" class="btn btn-sm btn-success">Ir al inicio de sesión</a>
        </div>
      </div>

      <!-- Formulario (se oculta si hubo éxito) -->
      <form *ngIf="!successMsg" [formGroup]="form" (ngSubmit)="onSubmit()" novalidate>

        <!-- Nombre -->
        <div class="mb-3">
          <label class="form-label fw-semibold">Nombre completo</label>
          <input
            type="text"
            formControlName="name"
            class="form-control"
            [class.is-invalid]="name.invalid && name.touched"
            placeholder="Tu nombre"
          />
          <div class="invalid-feedback">
            <span *ngIf="name.errors?.['required']">El nombre es obligatorio</span>
            <span *ngIf="name.errors?.['minlength']">Mínimo 2 caracteres</span>
          </div>
        </div>

        <!-- Email -->
        <div class="mb-3">
          <label class="form-label fw-semibold">Correo electrónico</label>
          <input
            type="email"
            formControlName="email"
            class="form-control"
            [class.is-invalid]="email.invalid && email.touched"
            placeholder="correo@ejemplo.com"
          />
          <div class="invalid-feedback">
            <span *ngIf="email.errors?.['required']">El correo es obligatorio</span>
            <span *ngIf="email.errors?.['email']">Correo no válido</span>
          </div>
        </div>

        <!-- Contraseña -->
        <div class="mb-3">
          <label class="form-label fw-semibold">Contraseña</label>
          <input
            type="password"
            formControlName="password"
            class="form-control"
            [class.is-invalid]="password.invalid && password.touched"
            placeholder="Mínimo 6 caracteres"
          />
          <div class="invalid-feedback">
            <span *ngIf="password.errors?.['required']">La contraseña es obligatoria</span>
            <span *ngIf="password.errors?.['minlength']">Mínimo 6 caracteres</span>
          </div>
        </div>

        <!-- Teléfono (opcional) -->
        <div class="mb-3">
          <label class="form-label fw-semibold">
            Teléfono <span class="text-muted fw-normal">(opcional)</span>
          </label>
          <input
            type="tel"
            formControlName="phone"
            class="form-control"
            placeholder="Ej: 3001234567"
          />
        </div>

        <!-- Tipo de cuenta -->
        <div class="mb-3">
          <label class="form-label fw-semibold">Tipo de cuenta</label>
          <div class="d-flex gap-3">

            <div
              class="flex-fill border rounded-3 p-3 text-center"
              [class.border-primary]="role.value === 'buyer'"
              [class.bg-primary]="role.value === 'buyer'"
              [class.bg-opacity-10]="role.value === 'buyer'"
              style="cursor: pointer;"
              (click)="form.get('role')!.setValue('buyer')"
            >
              <div class="fs-4">🛒</div>
              <div class="fw-semibold small mt-1">Comprador</div>
              <div class="text-muted" style="font-size: 0.72rem;">Compra productos</div>
            </div>

            <div
              class="flex-fill border rounded-3 p-3 text-center"
              [class.border-primary]="role.value === 'seller'"
              [class.bg-primary]="role.value === 'seller'"
              [class.bg-opacity-10]="role.value === 'seller'"
              style="cursor: pointer;"
              (click)="form.get('role')!.setValue('seller')"
            >
              <div class="fs-4">🏪</div>
              <div class="fw-semibold small mt-1">Vendedor</div>
              <div class="text-muted" style="font-size: 0.72rem;">Publica productos</div>
            </div>

          </div>
        </div>

        <!-- Campos extra para vendedor (aparecen dinámicamente) -->
        <div *ngIf="isSeller" class="border rounded-3 p-3 mb-3 bg-light">
          <p class="small fw-semibold text-muted mb-3">
            <i class="bi bi-info-circle me-1"></i>
            Datos del negocio
          </p>

          <div class="mb-3">
            <label class="form-label fw-semibold">Nombre del negocio</label>
            <input
              type="text"
              formControlName="business_name"
              class="form-control"
              [class.is-invalid]="business_name.invalid && business_name.touched"
              placeholder="Ej: Agua Pura S.A.S"
            />
            <div class="invalid-feedback">El nombre del negocio es obligatorio</div>
          </div>

          <div class="mb-1">
            <label class="form-label fw-semibold">NIT</label>
            <input
              type="text"
              formControlName="nit"
              class="form-control"
              [class.is-invalid]="nit.invalid && nit.touched"
              placeholder="Ej: 900123456-1"
            />
            <div class="invalid-feedback">El NIT es obligatorio</div>
          </div>
        </div>

        <!-- Botón submit -->
        <button
          type="submit"
          class="btn btn-primary w-100 mt-2"
          [disabled]="loading"
        >
          <span *ngIf="loading" class="spinner-border spinner-border-sm me-2"></span>
          {{ loading ? 'Registrando...' : 'Crear cuenta' }}
        </button>

      </form>

      <!-- Link al login -->
      <hr class="my-4">
      <p class="text-center small mb-0">
        ¿Ya tienes cuenta?
        <a routerLink="/auth/login" class="fw-semibold">Inicia sesión</a>
      </p>

    </div>
  </div>
</div>
